### PR TITLE
Change access permisions

### PR DESCRIPTION
**Pull request by ongda**
It should work now; let me know if play store still has issues D:

### CODE REVIEW

**Comment by ongda** [comment]
I think the "crashing" was from me not prompting for permissions.
I thought I only had to do it 1x but I guess not. I threw the prompt and checks at both places now so it should be good.

If not, let me know please!

**Comment by ongda** [comment]
It works now

and the fix was so simple yet ... I could not realize it until now ... ;__;

**Comment by ongda** [comment]
Annd I lied; now my problem is sort of in reverse....

User opens it (first time) = all = good
User tries to open it again later = bad :(

**Comment by ongda** [comment]
Issue: 

origin (aka current lat and lng) is getting made via prompt. But the prompt doesn't happen every time. Rather, it only happens 1x and then gets saved to memory. So...origin doesn't get made when you go visit Map Page after the 1st time.

But Idk where else to put it :o Maybe i'll force the prompt all the time?
Suggestions greatly appreciated! :D

**Review by foxj17 — APPROVED** [review]

**Review by jamesonn — APPROVED** [review]

**Pull request merged**
